ItemNames:
	db "Lunatic Orb@"
	db "Hard Orb@"
	db "Normal Orb@"
	db "Easy Orb@"
	db "Town Map@"
	db "Bicycle@"
	db "Surf Board@"	;joenote - give the surfboard it's fan name instead of ?????
	db "Extra Orb@"
	db "TH-Dex@"
	db "Moon Stone@"
	db "Antidote@"
	db "Burn Heal@"
	db "Ice Heal@"
	db "Awakening@"
	db "Parlyz Heal@"
	db "Full Restore@"
	db "Max Potion@"
	db "Hyper Potion@"
	db "Super Potion@"
	db "Potion@"
	db "BoulderBadge@"
	db "CascadeBadge@"
	db "ThunderBadge@"
	db "RainbowBadge@"
	db "SoulBadge@"
	db "MarshBadge@"
	db "VolcanoBadge@"
	db "EarthBadge@"
	db "Escape Rope@"
	db "Repel@"
	db "Old Amber@"
	db "Fire Stone@"
	db "ThunderStone@"
	db "Water Stone@"
	db "HP Up@"
	db "Protein@"
	db "Iron@"
	db "Carbos@"
	db "Calcium@"
	db "MysteryCandy@"
	db "Dome Fossil@"
	db "Helix Fossil@"
	db "Secret Key@"
;	db "?????@"
	db "Mist Stone@"	;joenote - custom item
	db "Bike Voucher@"
	db "X Accuracy@"
	db "Leaf Stone@"
	db "Card Key@"
	db "Nugget@"
	;db "PP UP@"	;unused PP_UP
	db "M. Gene@"	;joenote - custom item
	db "<pkmn> Doll@"
	db "Full Heal@"
	db "Revive@"
	db "Max Revive@"
	db "Guard Spec.@"
	db "Super Repel@"
	db "Max Repel@"
	db "Dire Hit@"
	db "Coin@"
	db "Fresh Water@"
	db "Soda Pop@"
	db "Lemonade@"
	db "S.S.Ticket@"
	db "Gold Teeth@"
	db "X Attack@"
	db "X Defend@"
	db "X Speed@"
	db "X Special@"
	db "Coin Case@"
	db "Oak's Parcel@"
	db "Itemfinder@"
	db "Silph Scope@"
	db "<pkmn> Flute@"
	db "Lift Key@"
	db "Exp.All@"
	db "Old Rod@"
	db "Good Rod@"
	db "Super Rod@"
	db "PP Up@"
	db "Ether@"
	db "Max Ether@"
	db "Elixer@"
	db "Max Elixer@"
	db "B2F@"
	db "B1F@"
	db "1F@"
	db "2F@"
	db "3F@"
	db "4F@"
	db "5F@"
	db "6F@"
	db "7F@"
	db "8F@"
	db "9F@"
	db "10F@"
	db "11F@"
	db "B4F@"
