MoveNames::
	db "Pound@"
	db "Karate Chop@"
	db "Double Slap@"
	db "Comet Punch@"
	db "Shadow Punch@"
	db "Miko Charity@"
	db "Fire Punch@"
	db "Ice Punch@"
	db "ThunderPunch@"
	db "Scratch@"
	db "Vicegrip@"
	db "Judgment@"
	db "Razor Wind@"
	db "Strawberry C@"
	db "Cut@"
	db "Gust@"
	db "Wing Attack@"
	db "Whirlwind@"
	db "Fly@"
	db "Silencing@"
	db "Slam@"
	db "Vine Whip@"
	db "Stomp@"
	db "Double Kick@"
	db "Mega Kick@"
	db "Jump Kick@"
	db "Rolling Kick@"
	db "Sand-Attack@"
	db "Headbutt@"
	db "Knife Throw@"
	db "Fury Attack@"
	db "S. Sculpture@"
	db "Tackle@"
	db "Body Slam@"
	db "Wrap@"
	db "Take Down@"
	db "Thrash@"
	db "Double-Edge@"
	db "Tail Whip@"
	db "Poison Sting@"
	db "Seal Needle@"
	db "HomingNeedle@"
	db "Leer@"
	db "Bite@"
	db "Growl@"
	db "Roar@"
	db "Sing@"
	db "Jamming@"
	db "Sonicboom@"
	db "Pvt. Square@"
	db "Acid@"
	db "Ember@"
	db "Flamethrower@"
	db "Mist@"
	db "Water Gun@"
	db "Hydro Pump@"
	db "Surf@"
	db "Ice Beam@"
	db "Blizzard@"
	db "Psybeam@"
	db "Bubblebeam@"
	db "Aurora Beam@"
	db "Master Spark@"
	db "Feather Jab@"
	db "Dragon Drill@"
	db "Submission@"
	db "Tension Kick@"
	db "Counter@"
	db "Seismic Toss@"
	db "Strength@"
	db "Absorb@"
	db "Mega Drain@"
	db "Leech Seed@"
	db "Growth@"
	db "Razor Leaf@"
	db "Solarbeam@"
	db "PoisonPowder@"
	db "Stun Spore@"
	db "Sleep Powder@"
	db "Sakura Storm@"
	db "Doll Strings@"
	db "DragonMeteor@"
	db "Fire Spin@"
	db "Thundershock@"
	db "Thunderbolt@"
	db "Thunder Wave@"
	db "Thunder@"
	db "Rock Throw@"
	db "Earthquake@"
	db "Hisou Sword@"
	db "Dig@"
	db "Toxic@"
	db "Confusion@"
	db "Psychic@"
	db "Hypnosis@"
	db "Envy@"
	db "Agility@"
	db "Quick Attack@"
	db "Rage@"
	db "Teleport@"
	db "Night Shade@"
	db "Third Eye@"
	db "Screech@"
	db "Double Team@"
	db "Recover@"
	db "Harden@"
	db "Minimize@"
	db "Smokescreen@"
	db "Confuse Ray@"
	db "Isolation@"
	db "Defense Curl@"
	db "Barrier@"
	db "Light Screen@"
	db "Black Wind@"
	db "Reflect@"
	db "Focus Energy@"
	db "Coerce@"
	db "Metronome@"
	db "Mirror Move@"
	db "Selfdestruct@"
	db "Artful S.@"
	db "Lick@"
	db "Pain Flow@"
	db "Sludge@"
	db "Mallet Smash@"
	db "Fire Blast@"
	db "Waterfall@"
	db "LittleLegion@"
	db "Swift@"
	db "Skull Bash@"
	db "PWJ Needle@"
	db "Oni Binding@"
	db "Amnesia@"
	db "Luna Dial@"
	db "Softboiled@"
	db "Wriggle Kick@"
	db "L. Red-Eyes@"
	db "Dream Eater@"
	db "PoisonBreath@"
	db "Barrage@"
	db "Leech Life@"
	db "Lovely Kiss@"
	db "Sky Attack@"
	db "Transform@"
	db "Bubble@"
	db "Dizzy Punch@"
	db "Spore@"
	db "Flash@"
	db "Psywave@"
	db "Focus Flight@"
	db "Disperse@"
	db "Pipice@"
	db "Explosion@"
	db "Fury Swipes@"
	db "Train Wreck@"
	db "Rest@"
	db "Rock Slide@"
	db "Life Counter@"
	db "Sharpen@"
	db "Conversion@"
	db "5-Element@"
	db "Super Fang@"
	db "Slash@"
	db "Substitute@"
	db "Struggle@"

