TrainerNames:
	db "Youngster@"
	db "Fae Catcher@"
	db "Lass@"
	db "Sailor@"
	db "Jr.Trainer@"
	db "Jr.Trainer@"
	db "<pkmn> Maniac@"
	db "Super Nerd@"
	db "Hiker@"
	db "Biker@"
	db "Burglar@"
	db "Engineer@"
	db "Juggler@"
	db "Fisherman@"
	db "Swimmer@"
	db "Cue Ball@"
	db "Gambler@"
	db "Beauty@"
	db "Psychic@"
	db "Rocker@"
	db "Juggler@"
	db "Tamer@"
	db "Winged Keeper@"
	db "Blackbelt@"
	db "Rival@"
	db "Prof.Oak@"
	db "Chief@"
	db "Scientist@"
	db "Giovanni@"
	db "Rocket@"
	db "Cool Trainer@"
	db "Cool Trainer@"
	db "Bruno@"
	db "Brock@"
	db "Misty@"
	db "Lt.Surge@"
	db "Erika@"
	db "Koga@"
	db "Blaine@"
	db "Sabrina@"
	db "Gentleman@"
	db "Rival@"
	db "Rival@"
	db "Lorelei@"
	db "Channeler@"
	db "Agatha@"
	db "Lance@"
